spring.application.name=DoAnJava
server.port=8088

#spring.data.mongodb.uri=mongodb://localhost:27017/chat_application

spring.data.mongodb.database=chat_application
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://hienxadoi2020:Ubd9oIyQrXwg1mjr@cluster0.ba9zymh.mongodb.net/chat_application?retryWrites=true&w=majority&appName=Cluster0

# Vô hi?u hóa c?u hình t? ??ng cho DataSource
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



